### ISSUE TITLE
Add possibility to fine-tune on other tasks

### ISSUE THREAD

**Issue by mmuffo94** [microsoft/fastformers#13]
# 🚀 Feature request
Hi,
Currently this repo only supports fine-tuning for SuperGlue tasks, am I right? Are you going to enable fine-tuning for other tasks as, for example, a generic sequence classification problem?

## Motivation

I believe that fine-tuning on SuperGlue tasks only strongly limits the applicability of Fastformers

**Comment by ykim362** [comment]
Thanks for the comment, @mmuffo94!
The main purpose of this repository is to demonstrate the models from the FastFormers paper.
At the moment, we are not planning to expand the scope.
