### ISSUE TITLE
fastformer

### ISSUE THREAD

**Issue by HWNHJJ** [microsoft/fastformers#18]
Thank you very much for your work. I would like to ask where the code corresponding to fastformer is and intend to use it in visual tasks.

**Comment by ykim362** [comment]
Hi @HWNHJJ. Thanks for your interest!. It's intended for transformer architectures in general. It should work for any transformers in terms of functionality as long as the data processing pipeline is added correctly, but we haven't tested the accuracy on visual tasks.
