### ISSUE TITLE
AMD CPUs should work just fine 

### ISSUE THREAD

**Issue by LifeIsStrange** [microsoft/fastformers#2]
The README mentions Intel cpus are required because of the necessity of AVX256 support. 

First of all AMD cpu supports AVX 256 since a Long time (jaguar which predate zen).
True AVX 256 support (not only being compatible but being twice as fast as AVX 128) came one year ago with ZEN 2 cpus.

Zen 3 cpus are now being released and are the fastest cpus in the world and any Deep learning researchers should have them and be compatible with them, period.

**Comment by ykim362** [comment]
Thanks for your opinion.
We haven't tested the models on AMD CPUs. This is currently out of our scope of the project. It may or may not work correctly, but we don't actively maintain AMD environment.

**Comment by LifeIsStrange** [comment]
I understand that you haven't tested it on AMD but you simply shouldn't have to, unless you use a custom niche compiler, it should work just fine on any compliant x86-64 CPU.
I you still want to only mention Intel in the Readme out of paranoïa (sorry for the choice of word) it's fine but it will mislead users not to try your software because of a non existent risk.

Sidenotes:
Microsoft azure sell an increasing number of AMD epycs cpus. 
The Xbox serie X of Microsoft is AMD based and use deep learning to some extent so they might use fastformers eventually.

**Comment by ykim362** [comment]
Do you know if AMD CPUs have 8-bit integer fused multiply add instructions? I am not familiar with AMD CPUs, and I looked it up quickly our of my curiosity, but I couldn't find one. 8-bit integer FMA is one of the key factors to improve the efficiency.

https://software.intel.com/content/www/us/en/develop/articles/lower-numerical-precision-deep-learning-inference-and-training.html

If you look at the paper, Intel AVX2 and AVX512 CPUs have `VPMADDUBSW` or `VPDPBUSD`.  To get the 8-bit quantized model running, one of those or equivalent instructions are needed.

**Comment by ykim362** [comment]
I will update the README. Thanks for your opinion.
