### ISSUE TITLE
Support for XLnet

### ISSUE THREAD

**Issue by LifeIsStrange** [microsoft/fastformers#3]
XLnet is supported by Transformers and in 2020 still remains the pre trained language model with the most SOTA on paperswithcode.com (far beyond BERT, Albert & ci)

**Comment by ykim362** [comment]
Thanks for the opinion. We will look at if we can support this in the future.

**Comment by ykim362** [comment]
The main purpose of this repository is to demonstrate the models from the FastFormers paper.
At the moment, we are not planning to expand the scope.
Thank you.
