### ISSUE TITLE
Run the teacher model (BERT-base) baseline Error

### ISSUE THREAD

**Issue by baiziyuandyufei** [microsoft/fastformers#4]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): BERT

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [x] the official example scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name)

## To reproduce

1.  run the command below
```
python examples\fastformers\run_superglue.py --model_type bert --model_name_or_path ..\model\fastformers\teacher_model\teacher-bert-base  --task_name BoolQ --output_dir .\out --do_eval  --data_dir ..\dataset\fastformers\BoolQ --per_instance_eval_batch_size 1 --use_fixed_seq_length --do_lower_case --max_seq_length 512 --no_cuda
```

## Expected behavior

get error below:

FileNotFoundError: [Errno 2] No such file or directory: '..\\dataset\\fastformers\\BoolQ\\tensors_dev_..\\model\\fastformers\\teacher_model\\teacher-bert-base_512_boolq_True'

## Environment info

     
- `transformers` version: 2.11.0
- Platform: windows
- Python version: 3.6
- PyTorch version (GPU?): 1.7.0+cpu
- Tensorflow version (GPU?):  None
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by ykim362** [comment]
As mentioned in the readme, we don't support this on windows at the moment. Could you try this on linux? It works well on WSL as well.

**Comment by baiziyuandyufei** [comment]
@ykim362 Thank you! On ubuntu16.04, everything is OK.
